apiVersion: v1
kind: Service
metadata:
  name: graphite-api
  namespace: default
  labels:
    app: graphite
spec:
  externalTrafficPolicy: Local
  ports:
  - name: api
    port: 2003
    protocol: TCP
    targetPort: 2003
  selector:
    app: graphite
  type: NodePort
