apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: default
  labels:
    app: influxdb
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:    
    app: influxdb
  type: NodePort
