apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data:
  graphite.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "graphite",
                "orgId": 1,
                "type": "graphite",
                "url": "http://graphite-http.default.svc:8080",
                "version": 1
            }
        ]
    }
